### ISSUE TITLE
Model Architecture

### ISSUE THREAD

**Issue by sr229** [vignette-project/backend#1]
To have an idea of what we want, we want to focus on these three objectives:

- We want to be able to run inference even on a Raspberry Pi 4B (to be honest this is the lowest we can go).
- We want our face tracking to have least latency as possible (~40ms is acceptable, anything higher than 50ms is not tolerable).
- We want to be able to predict the facial features along with tracking the eye gaze
- We want to also perform transfer learning.

## Background

Current implementations like FaceRig uses static models and does a poor job at tracking faces properly. This is what we want to avoid with our implementation. To do that, we would use a Convolutional Neural Network that is pre-trained but has the ability to do unsupervised transfer learning, and we want to do it as long as the program that runs the model is running. 

The reason we would want our face tracking to continually improve itself as it learns more about the face of the user is to allow us to develop the neural network without making any changes on the dataset, the model should be at least improve on itself.

## Proposed Approach

I plan at the moment to do a variant of Faster R-CNN with a modification to allow it to keep training unsupervised. This would reduce the need to maintain the neural net but still leaving room for proper improvements in the near future.  @gmlwns2000 mentioned we can use ONNX which makes sense but I wonder if it performs just as well with minimal CPU overhead if it can't find a suitable acceleratro.

**Comment by gmlwns2000** [comment]
@sr229 

Ah, SharpFace. It is originally from OpenFace/Tadas, and it was 0.1 beta when I tried to use it, and now it's 2.0. So it would be not a good idea to use the current SharpFace. I left the repository for my backward compatibilities for other personal projects. To use we should upgrade and upgrade API to 2.0 would be a huge job.

And also I saw some about the commercializing of this project, and open-face is prohibited from commercial use. They should be paid.

I check the OpenFace 2.0 paper, and they use MTCNN and CE-CLM (Multiple CNN for smaller specific regions). And then they speed up the process by object tracking the bounding box. They optimized quite well in CPU computation flow, but they don't use GPU resources, so it could be a todo point.

To use mobile-net SSD or MTCNN with ONNX for face detection is a good alternative of dlib too.

**MOVED from original issue

**Comment by sr229** [comment]
@gmlwns2000 preferrably we would like to do CPU inferencing since we want to assume our intrepid VTuber is using the GPU for graphical tasks. GPUs are known for HPC but I don't think they're designed to run more than one kind of program in one GPU, especially for older cards like AMD GCN4.

**Comment by sr229** [comment]
We might actually go for TensorFlowSharp using the [3DDFA](https://github.com/cleardusk/3DDFA) as a better solution to fully track the face.

**Comment by sr229** [comment]
(PS: Forgot we might actually just opt in to make the 3DDFA backend a seperate .NET Library, similar to SharpFace.)
